### ISSUE TITLE
peer dependency versioning issue?

### ISSUE THREAD

**Issue by epaulson** [georgeOsdDev/react-fileupload-progress#15]
I'm sort of an npm-newbie, but I've had some struggles with react versions between react 0.15 and react-fileupload-progress.

Bootstrapping a react app using
https://github.com/facebookincubator/create-react-app

gives a "recommended" base version of react/webpack/babel etc.
I create a a clean demo project like so:
create-react-app reactuploadtest

However, adding react-fileupload-progress gives me some warnings about unmet peer dependencies:

epaulson:~/Desktop/django-experiments/drf/react-bootstrap-tests/reactuploadtest $ npm install --save react-fileupload-progress
reactuploadtest@0.0.1 /Users/epaulson/Desktop/django-experiments/drf/react-bootstrap-tests/reactuploadtest
├── UNMET PEER DEPENDENCY react@15.3.1
├── UNMET PEER DEPENDENCY react-dom@15.3.1
└─┬ react-fileupload-progress@0.3.2 
  ├─┬ react@0.14.8 
  │ ├─┬ envify@3.4.1 
  │ │ ├─┬ jstransform@11.0.3 
  │ │ │ ├── base62@1.1.1 
  │ │ │ ├─┬ commoner@0.10.4 
  │ │ │ │ ├─┬ commander@2.9.0 
  │ │ │ │ │ └── graceful-readlink@1.0.1 
  │ │ │ │ ├─┬ detective@4.3.1 
  │ │ │ │ │ ├── acorn@1.2.2 
  │ │ │ │ │ └── defined@1.0.0 
  │ │ │ │ ├─┬ glob@5.0.15 
npm WARN react-fileupload-progress@0.3.2 requires a peer of react@^0.14.6 but none was installed.
npm WARN react-fileupload-progress@0.3.2 requires a peer of react-dom@^0.14.6 but none was installed.
? inflight@1.0.5 
  │ │ │ │ │ │ └── wrappy@1.0.2 
  │ │ │ │ │ ├─┬ minimatch@3.0.3 
  │ │ │ │ │ │ └─┬ brace-expansion@1.1.6 
  │ │ │ │ │ │   ├── balanced-match@0.4.2 
  │ │ │ │ │ │   └── concat-map@0.0.1 
  │ │ │ │ │ ├── once@1.3.3 
  │ │ │ │ │ └── path-is-absolute@1.0.0 
  │ │ │ │ ├── graceful-fs@4.1.6 
  │ │ │ │ ├─┬ mkdirp@0.5.1 
  │ │ │ │ │ └── minimist@0.0.8 
  │ │ │ │ ├── private@0.1.6 
  │ │ │ │ ├── q@1.4.1 
  │ │ │ │ └─┬ recast@0.10.43 
  │ │ │ │   ├── ast-types@0.8.15 
  │ │ │ │   ├── esprima-fb@15001.1001.0-dev-harmony-fb 
  │ │ │ │   └── source-map@0.5.6 
  │ │ │ ├── esprima-fb@15001.1.0-dev-harmony-fb 
  │ │ │ ├── object-assign@2.1.1 
  │ │ │ └─┬ source-map@0.4.4 
  │ │ │   └── amdefine@1.0.0 
  │ │ └── through@2.3.8 
  │ └─┬ fbjs@0.6.1 
  │   └── whatwg-fetch@0.9.0 
  ├── react-dom@0.14.8 
  └─┬ sinon@1.17.5 
    ├── formatio@1.1.1 
    ├── lolex@1.3.2 
    ├── samsam@1.1.2 
    └─┬ util@0.10.3 
      └── inherits@2.0.1 

In my other project where I was using react-fileupload, I ran into all sorts of trouble with strange complaints from react telling me that it might have multiple versions installed, similar to some of the troubles reported here:
https://gist.github.com/jimfb/4faa6cbfb1ef476bd105
(it's possible I somehow made things worse. I tried deleting my node_modules and reinstalling with npm install a few times)

I ultimately solved them by just forking react-fileupload and bumping the version in package.json in my repo to be the current release, but that seems like it's the wrong way to solve the problem.  (though I don't know what the right way to solve it might be)

**Comment by mscheper** [comment]
FWIW, I'm having a similar problem with [react-way-getting-started](https://github.com/RisingStack/react-way-getting-started) and another module:
`npm WARN react-dom@15.3.1 requires a peer of react@^15.3.1 but none was installed`
True enough, I had React 0.13.3 installed (not as old as it looks, because I think they went from 0.14 to just 15).

The part that might be helpful: I got around this by typing `npm install --save 'react@^15'`.

For me, however, updating just broke a lot of code. ☹ And I realised that I've been trying to use different bits of different versions of React. I don't think I need to, and I certainly don't think my original problem is worth going down that rabbit hole. So I've reverted my package.json file, typed `npm remove react-dom` to get rid of the error I was still seeing in `npm install`, and gone back to where I started.

I hope this helps, or that you've at least found an alternative third-party library for whatever you're doing.

**Comment by georgeOsdDev** [comment]
I have updated npm dependencies and released react-fileupload-progress@0.4.0
302f9ca775a622e9ddd0bb54bd5dea5a10da05af

I'm not well understood about npm peer dependencies,
but in my opinion, supporting older react( < 15) is not effective, so I put peer dependencies as 15.x
Please try react-fileupload-progress@0.4.0

**Comment by abhishek-servicemax** [comment]
I am facing error while uploading files after updating react 15.x to 16.0.0

this.updater.enqueueCallback is not a function
    at FileUploadProgress../node_modules/react-fileupload-progress/node_modules/react/lib/ReactBaseClasses.js.ReactComponent.setState 
I don't want to come back on react15.x 

Please help me anyone on this.

**Comment by kubakunc** [comment]
+1

**Comment by georgeOsdDev** [comment]
I've released
`react-fileupload-progress@0.4.1`
inclued #25, #26 
Please check latest one.
